
function  name = numberToName (num)     
    names = ["0:Maxim 20", "1: Maxim 30", "2:Maxim 50", "3:Maxim 60", "4:Maxim 70", "5:Maxim 80", "6:Final tram 80", ...
            "7:Maxim 100", "8:Maxim 120", "9:Prohibit avançar", "10:Prohibit avançar camions", "11:Encreuament", ...
            "12:Prioritat al encreuament", "13:Cedeixi el pas", "14:Stop", "15:Prohibida la circulació",...
            "16:prohibida circulació camions", "17:Prohibit el pas", "18:Perill proper", "19:Revolt pronunciat esquerra", ...
            "20:Revolt pronunciat dreta", "21:Revolts pronunciats", "22:Baden", "23:Terreny relliscos", ...
            "24:Estretament dret", "25:Obres", "26:Semàfor", "27:Pas de vianants", "28:Perill d'escola", "29:Ciclos" ,...
            "30:Perill General *", "31:Perill animals salvatges", "32:Final prohibició",...
            "33:Recomanació gir dret", "34:Recomanació gir esquerra", "35:Recomanació recte", "36:Recomanació recte/dreta", ...
            "37:Recomanació recte/dreta", "38:Recomanació dreta-38", "39:Recomanació esquerra-39", "40:Rotonda", ...
            "41:Fi regió d'avançament"];
    name = names(num);
    
end


